### PR TITLE
Changed notificator to condulum/notificator for now.

### PR DESCRIPTION
**Pull request by condulum**
I have modified the notificator so that macOS notification is now supported. I changed the dependencies (import) to my fork. Can be reverted to 0xAX’s once notificator’s PR was accepted.

### CODE REVIEW

**Comment by jonas747** [comment]
hm looks good except https://github.com/condulum/notificator/commit/524707d118be49ef3ea39eed42244651322c2cd7#diff-d05ebdd8cedfeb5061f9938d020fd594R166

This will say version 11.1 is below 10.9

**Comment by condulum** [comment]
this is why you don't code at 5AM. Rookie error...

**Comment by condulum** [comment]
fixed.

**Comment by jonas747** [comment]
can you run `go fmt` on it? big thanks man

**Comment by condulum** [comment]
done, I ran the whole project through gofmt.

**Comment by jonas747** [comment]
Thanks

**Pull request merged**
